//! GECCO marginal conformance tests.
//!
//! Verifies that marginal probabilities from the Rust library API match
//! the original C CRFsuite binary when using the real GECCO biosynthetic
//! gene cluster model.  This catches regressions that would cause the Rust
//! reimplementation to over- or under-predict cluster probabilities.
//!
//! Test data: three 20-gene windows from CP157504.1 (Streptomyces), each
//! exercising a different probability range:
//!   - window_start:   near-zero probabilities (non-cluster region)
//!   - window_cluster: rising probabilities (entering a BGC)
//!   - window_mid:     mixed low/medium probabilities
//!
//! Ground truth generated by sklearn-crfsuite 0.5.0 (Python wrapper around
//! the original C CRFsuite library) and cross-checked against the C binary.

#![allow(clippy::excessive_precision)]

use std::path::PathBuf;
use std::process::Command;

use crfsuite_compliant_rs::crf1d::tag::Crf1dTagger;
use crfsuite_compliant_rs::model::ModelReader;
use crfsuite_compliant_rs::types::{Attribute, Instance, Item};

// ── helpers ────────────────────────────────────────────────────────────────

fn project_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn rust_bin() -> PathBuf {
    if let Some(bin) = option_env!("CARGO_BIN_EXE_crfsuite-compliant-rs") {
        return PathBuf::from(bin);
    }
    project_root().join("target/debug/crfsuite-compliant-rs")
}

fn test_data(name: &str) -> PathBuf {
    project_root().join("test_data").join(name)
}

fn gecco_model_path() -> PathBuf {
    test_data("gecco_model.crfsuite")
}

fn gecco_model_bytes() -> Option<Vec<u8>> {
    let path = gecco_model_path();
    if !path.exists() {
        eprintln!("SKIP: test_data/gecco_model.crfsuite missing");
        return None;
    }
    Some(std::fs::read(path).expect("read GECCO model"))
}

fn gecco_iwa_path(name: &str) -> Option<PathBuf> {
    let path = test_data(name);
    if !path.exists() {
        eprintln!("SKIP: {name} missing");
        return None;
    }
    Some(path)
}

/// Build an Instance from a list of feature-name lists, the way gecco-rs does.
/// Each inner Vec<&str> is the set of Pfam domain names present for one gene.
fn build_instance(model: &ModelReader, features: &[Vec<&str>]) -> Instance {
    let items: Vec<Item> = features
        .iter()
        .map(|feat_list| {
            let attrs: Vec<Attribute> = feat_list
                .iter()
                .filter_map(|name| model.to_aid(name).map(|aid| Attribute { aid, value: 1.0 }))
                .collect();
            Item { contents: attrs }
        })
        .collect();

    Instance {
        items,
        labels: vec![0i32; features.len()],
        weight: 1.0,
        group: 0,
    }
}

/// Get marginal P(label="1" | x) for each position via the library API.
fn library_marginals(model: &ModelReader, features: &[Vec<&str>]) -> Vec<f64> {
    let mut tagger = Crf1dTagger::new(model);
    let inst = build_instance(model, features);
    tagger.set(&inst);

    let label_1 = model.to_lid("1").expect("model must have label '1'");
    (0..features.len())
        .map(|t| tagger.marginal_point(label_1, t as i32))
        .collect()
}

fn canonical_library_marginals(model: &ModelReader, features: &[Vec<&str>]) -> Vec<f64> {
    let mut tagger = Crf1dTagger::new(model);
    let inst = build_instance(model, features);
    tagger.set_canonical(&inst);

    let label_1 = model.to_lid("1").expect("model must have label '1'");
    (0..features.len())
        .map(|t| tagger.marginal_point(label_1, t as i32))
        .collect()
}

/// Parse marginals from C/Rust CLI `-l` output.
/// Each line looks like: `0\t0:0.999998\t1:0.000002`
fn parse_cli_marginals(output: &str) -> Vec<f64> {
    output
        .lines()
        .filter(|line| !line.is_empty() && !line.starts_with('@'))
        .map(|line| {
            // Find the field that starts with "1:"
            line.split('\t')
                .find_map(|field| field.strip_prefix("1:").map(|v| v.parse::<f64>().unwrap()))
                .expect("no 1:value field in CLI output line")
        })
        .collect()
}

// ── test window definitions ────────────────────────────────────────────────

/// Window at position 0: low-probability non-cluster region.
fn window_start_features() -> Vec<Vec<&'static str>> {
    vec![
        vec![
            "PF00004", "PF13173", "PF13245", "PF01637", "PF00308", "PF08299", "PF11638", "PF01695",
        ],
        vec!["PF00712", "PF02767", "PF02768"],
        vec!["PF13275"],
        vec![
            "PF13175", "PF13304", "PF13476", "PF13514", "PF13555", "PF02463",
        ],
        vec!["PF00204", "PF00986", "PF02518", "PF13589", "PF01751"],
        vec![],
        vec!["PF03989", "PF00521"],
        vec![],
        vec!["PF01081", "PF00571", "PF01070", "PF01645", "PF03060"],
        vec!["PF13354", "PF07943", "PF00768"],
        vec![
            "PF02639", "PF01207", "PF00977", "PF03060", "PF01680", "PF05690",
        ],
        vec!["PF01965", "PF07685", "PF13507", "PF03575", "PF01174"],
        vec!["PF10186", "PF03462", "PF02403", "PF00587"],
        vec![
            "PF13191", "PF13207", "PF13238", "PF13481", "PF13671", "PF07728", "PF00005", "PF01656",
            "PF13189", "PF01712", "PF05729", "PF00931", "PF10609", "PF03193", "PF01202", "PF02223",
            "PF02367",
        ],
        vec![
            "PF00004", "PF13191", "PF13207", "PF13238", "PF13671", "PF07728", "PF02224", "PF01712",
            "PF08433", "PF05729", "PF00931", "PF01202", "PF02223", "PF02367",
        ],
        vec!["PF00704", "PF01476"],
        vec!["PF00857"],
        vec!["PF00383", "PF14437", "PF17917", "PF17919"],
        vec![
            "PF00004", "PF13173", "PF13191", "PF13238", "PF13245", "PF13479", "PF13604", "PF07728",
            "PF16193", "PF00005", "PF13177", "PF12169", "PF01935", "PF01078", "PF05496", "PF00158",
            "PF01202", "PF00437", "PF10412", "PF02367",
        ],
        vec!["PF00669", "PF02575"],
    ]
}

/// Expected P("1") values from sklearn-crfsuite / C CRFsuite.
fn window_start_expected() -> Vec<f64> {
    vec![
        1.240870206104821e-09,
        4.718270090675179e-07,
        1.313553245854102e-06,
        3.971399936935095e-11,
        1.997017344533998e-05,
        3.592490514001974e-05,
        5.117163260775792e-08,
        2.671193785011240e-05,
        5.590091745923837e-07,
        1.110580313578095e-05,
        1.097349785895917e-10,
        7.717623904354623e-11,
        4.456697462571396e-04,
        3.734856619051808e-10,
        9.059454730880117e-12,
        1.929194469415363e-06,
        5.004923945628770e-04,
        1.145131361380032e-03,
        1.338280047927771e-18,
        7.915420316198468e-05,
    ]
}

/// Window near cluster at ~623 kbp: rising probabilities.
fn window_cluster_features() -> Vec<Vec<&'static str>> {
    vec![
        vec!["PF01844", "PF01258"],
        vec![],
        vec![],
        vec![],
        vec![
            "PF12848", "PF04977", "PF07195", "PF02050", "PF02195", "PF04012",
        ],
        vec![],
        vec![],
        vec![],
        vec!["PF01757", "PF01027"],
        vec![],
        vec!["PF00733", "PF12481", "PF13522", "PF13537"],
        vec![
            "PF02737", "PF01593", "PF01266", "PF00890", "PF01494", "PF12831", "PF01134", "PF03486",
            "PF13450", "PF13454", "PF00070", "PF13738",
        ],
        vec![
            "PF01593", "PF01266", "PF00890", "PF01494", "PF12831", "PF03486", "PF13450", "PF13454",
            "PF00070",
        ],
        vec!["PF00494"],
        vec!["PF00128", "PF16657"],
        vec![
            "PF12728", "PF01381", "PF00356", "PF00532", "PF13377", "PF13407",
        ],
        vec!["PF00171"],
        vec!["PF00155", "PF00202", "PF01043"],
        vec!["PF01546", "PF04389"],
        vec!["PF00324", "PF13520"],
    ]
}

fn window_cluster_expected() -> Vec<f64> {
    vec![
        1.791783474071162e-06,
        7.312349036013710e-05,
        9.652255500884885e-05,
        7.223331798853920e-05,
        2.143264306250874e-09,
        8.514618149853613e-05,
        1.237302412369588e-04,
        1.161572296567035e-04,
        6.234806693208957e-05,
        4.568642501238926e-03,
        9.501630373889418e-03,
        2.005760892728737e-02,
        4.435274927454626e-02,
        5.297529174798859e-02,
        1.342170381935078e-02,
        3.831941435555696e-03,
        3.534306110283200e-03,
        3.780598068706754e-03,
        5.511243070805740e-03,
        8.982097117136482e-03,
    ]
}

/// Window at position 2700: mixed region.
fn window_mid_features() -> Vec<Vec<&'static str>> {
    vec![
        vec!["PF17886", "PF00011"],
        vec![],
        vec!["PF08030"],
        vec![],
        vec!["PF03602", "PF08241", "PF13649", "PF03141", "PF13847"],
        vec![],
        vec![
            "PF01325", "PF08279", "PF12728", "PF13384", "PF13412", "PF13601", "PF01418", "PF08220",
            "PF04760", "PF01047", "PF12802", "PF01978",
        ],
        vec!["PF01066"],
        vec!["PF04011"],
        vec!["PF01022", "PF12802", "PF03965", "PF13091", "PF01978"],
        vec!["PF07690", "PF00083"],
        vec!["PF04463"],
        vec!["PF03780"],
        vec!["PF03631"],
        vec!["PF01757", "PF19853"],
        vec!["PF03597", "PF01235"],
        vec!["PF01235"],
        vec!["PF07690", "PF12832", "PF05977", "PF00083"],
        vec!["PF07690", "PF05977"],
        vec![],
    ]
}

fn window_mid_expected() -> Vec<f64> {
    vec![
        1.028832113878686e-02,
        1.051029649458716e-02,
        1.078994291262425e-02,
        9.358284296693766e-03,
        8.044179333120939e-03,
        3.844216124822668e-03,
        4.376408684878117e-16,
        4.477581466446051e-06,
        5.562670159635640e-08,
        1.256653329066191e-06,
        3.937069714869195e-05,
        2.492690348116571e-06,
        1.377278064921864e-05,
        1.442108470953124e-05,
        4.117083018591696e-05,
        3.009747570995704e-06,
        3.069049146540241e-04,
        3.760968533516577e-03,
        8.523441028208288e-03,
        1.355165826404806e-02,
    ]
}

// ── library API tests ──────────────────────────────────────────────────────

/// Assert library marginals match expected values within tolerance.
/// Uses relative tolerance for large values, absolute for near-zero.
fn assert_marginals_close(actual: &[f64], expected: &[f64], label: &str) {
    assert_eq!(actual.len(), expected.len(), "{label}: length mismatch");
    for (t, (a, e)) in actual.iter().zip(expected.iter()).enumerate() {
        let abs_diff = (a - e).abs();
        let rel_diff = if *e != 0.0 {
            abs_diff / e.abs()
        } else {
            abs_diff
        };
        // Allow 1e-4 relative or 1e-15 absolute (for near-zero values)
        assert!(
            rel_diff < 1e-4 || abs_diff < 1e-15,
            "{label} position {t}: got {a:.10e}, expected {e:.10e} (rel={rel_diff:.2e}, abs={abs_diff:.2e})"
        );
    }
}

#[test]
fn gecco_library_marginals_window_start() {
    let Some(data) = gecco_model_bytes() else {
        return;
    };
    let model = ModelReader::open(&data).unwrap();
    let actual = library_marginals(&model, &window_start_features());
    assert_marginals_close(&actual, &window_start_expected(), "window_start");
}

#[test]
fn gecco_library_marginals_window_cluster() {
    let Some(data) = gecco_model_bytes() else {
        return;
    };
    let model = ModelReader::open(&data).unwrap();
    let actual = library_marginals(&model, &window_cluster_features());
    assert_marginals_close(&actual, &window_cluster_expected(), "window_cluster");
}

#[test]
fn gecco_library_marginals_window_mid() {
    let Some(data) = gecco_model_bytes() else {
        return;
    };
    let model = ModelReader::open(&data).unwrap();
    let actual = library_marginals(&model, &window_mid_features());
    assert_marginals_close(&actual, &window_mid_expected(), "window_mid");
}

// ── CLI cross-validation tests ─────────────────────────────────────────────

macro_rules! skip_without_c {
    () => {
        let c = project_root().join("crfsuite/frontend/.libs/crfsuite");
        if !c.exists() {
            eprintln!("SKIP: C crfsuite binary not found");
            return;
        }
    };
}

fn run_cli(bin: &PathBuf, model: &str, iwa: &str, env: Option<(&str, PathBuf)>) -> String {
    let mut cmd = Command::new(bin);
    cmd.args(["tag", "-m", model, "-l", iwa]);
    if let Some((key, val)) = env {
        cmd.env(key, val);
    }
    let o = cmd.output().expect("spawn binary");
    assert!(
        o.status.success(),
        "{bin:?} failed: {}",
        String::from_utf8_lossy(&o.stderr)
    );
    String::from_utf8(o.stdout).unwrap()
}

/// Verify Rust CLI and C CLI produce identical marginals on the GECCO model.
#[test]
fn gecco_cli_marginals_vs_c() {
    skip_without_c!();

    let c_bin = project_root().join("crfsuite/frontend/.libs/crfsuite");
    let rs_bin = rust_bin();
    assert!(rs_bin.exists(), "Rust binary missing – run `cargo build`");

    let model_path = gecco_model_path();
    if !model_path.exists() {
        eprintln!("SKIP: test_data/gecco_model.crfsuite missing");
        return;
    }
    let model = model_path.to_str().unwrap().to_string();
    let lib_path = project_root().join("crfsuite/lib/crf/.libs");

    for window_name in ["window_start", "window_cluster", "window_mid"] {
        let Some(iwa_path) = gecco_iwa_path(&format!("gecco_iwa_{window_name}.txt")) else {
            return;
        };
        let iwa = iwa_path.to_str().unwrap().to_string();

        let c_out = run_cli(
            &c_bin,
            &model,
            &iwa,
            Some(("LD_LIBRARY_PATH", lib_path.clone())),
        );
        let rs_out = run_cli(&rs_bin, &model, &iwa, None);

        assert_eq!(c_out, rs_out, "CLI marginals differ for {window_name}");
    }
}

/// Verify library API matches CLI output for the GECCO model.
/// This catches bugs in how the library is called (Instance construction,
/// attribute mapping, etc.) vs the CLI's IWA parsing path.
#[test]
fn gecco_library_vs_cli_marginals() {
    let rs_bin = { rust_bin() };
    if !rs_bin.exists() {
        eprintln!("SKIP: Rust binary not built");
        return;
    }

    let model_path = gecco_model_path();
    if !model_path.exists() {
        eprintln!("SKIP: test_data/gecco_model.crfsuite missing");
        return;
    }
    let model_str = model_path.to_str().unwrap().to_string();
    let data = std::fs::read(&model_path).unwrap();
    let model = ModelReader::open(&data).unwrap();

    let cases: Vec<(&str, Vec<Vec<&str>>)> = vec![
        ("window_start", window_start_features()),
        ("window_cluster", window_cluster_features()),
        ("window_mid", window_mid_features()),
    ];

    for (name, features) in &cases {
        // Library API
        let lib_marginals = library_marginals(&model, features);

        // CLI
        let Some(iwa_path) = gecco_iwa_path(&format!("gecco_iwa_{name}.txt")) else {
            return;
        };
        let iwa = iwa_path.to_str().unwrap().to_string();
        let cli_out = run_cli(&rs_bin, &model_str, &iwa, None);
        let cli_marginals = parse_cli_marginals(&cli_out);

        assert_eq!(
            lib_marginals.len(),
            cli_marginals.len(),
            "{name}: length mismatch"
        );
        for (t, (lib_val, cli_val)) in lib_marginals.iter().zip(cli_marginals.iter()).enumerate() {
            let diff = (lib_val - cli_val).abs();
            // CLI rounds to 6 decimals, so allow 5e-7 tolerance
            assert!(
                diff < 5e-7,
                "{name} position {t}: library={lib_val:.10e}, cli={cli_val:.6}, diff={diff:.2e}"
            );
        }
    }
}

#[test]
fn gecco_canonical_marginals_are_attribute_order_independent() {
    let Some(data) = gecco_model_bytes() else {
        return;
    };
    let model = ModelReader::open(&data).unwrap();
    let mut features = window_start_features();
    let baseline = canonical_library_marginals(&model, &features);

    for item in &mut features {
        item.reverse();
    }
    let reversed = canonical_library_marginals(&model, &features);

    assert_eq!(baseline, reversed);
}
